#!/bin/sh
# scripts/fix-hermesc-arm64.sh
# ─────────────────────────────────────────────────────────────────────────
# Wraps the x86_64 hermesc binary with qemu so it can run on ARM64 Linux
# (Emergent's container is aarch64; react-native only ships an x86_64 build).
#
# Runs as a postinstall hook in package.json — idempotent, safe on x86_64
# (skips when not aarch64), no-op when qemu-x86_64-static isn't installed.
# Without this, `eas update` fails with:
#   /…/hermesc: 1: ELF: not found
set -eu

# Only touch hermesc on ARM64 — x86_64 hosts run the binary natively.
ARCH=$(uname -m 2>/dev/null || echo unknown)
case "$ARCH" in
  aarch64|arm64) ;;
  *) echo "[fix-hermesc] host is $ARCH — no wrapper needed"; exit 0 ;;
esac

HERMESC="$(dirname "$0")/../node_modules/react-native/sdks/hermesc/linux64-bin/hermesc"
if [ ! -e "$HERMESC" ] && [ ! -e "${HERMESC}.real" ]; then
  echo "[fix-hermesc] hermesc not found at $HERMESC — skipping"
  exit 0
fi

QEMU=$(command -v qemu-x86_64-static 2>/dev/null || true)
if [ -z "$QEMU" ]; then
  echo "[fix-hermesc] qemu-x86_64-static not installed — install with: apt-get install -y qemu-user-static"
  echo "[fix-hermesc] continuing without wrapper (eas update will fail until qemu is installed)"
  exit 0
fi

# Move the real binary out of the way (only on first run; subsequent yarn
# installs land a fresh x86_64 binary that needs re-wrapping).
if [ -e "$HERMESC" ]; then
  # If it's already our shell wrapper, leave it alone.
  if head -1 "$HERMESC" 2>/dev/null | grep -q '^#!/'; then
    echo "[fix-hermesc] wrapper already in place at $HERMESC"
    exit 0
  fi
  mv "$HERMESC" "${HERMESC}.real"
fi

cat > "$HERMESC" <<'EOF'
#!/bin/sh
# Auto-generated by scripts/fix-hermesc-arm64.sh — invokes the real x86_64
# hermesc binary through qemu so EAS update can compile Hermes bytecode on
# ARM64 hosts.
exec /usr/bin/qemu-x86_64-static "$(dirname "$0")/hermesc.real" "$@"
EOF
chmod +x "$HERMESC"
echo "[fix-hermesc] installed qemu wrapper at $HERMESC"
